### ISSUE TITLE
Tambah Menu Manajemen Stok

### ISSUE THREAD

**Issue by share424** [pradiptaagus/suta-store#5]
1. Tampilan awal seperti master data
2. Bisa melihat stok tiap produk (tiap varian, gunakan rumus modulus dan div)
3. Bisa menambahkan stok (stok yang selalu ditambahkan adalah satuan terbesar)

**Comment by pradiptaagus** [comment]
30c7ba4 - c350a84

**Comment by pradiptaagus** [comment]
stok yang ditambahkan mengikuti stok terkecil
